{
 "title": "INUCLEO",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "deviceName",
    "query": "SHOW TAG VALUES WITH KEY = \"deviceName\""
   }
  ]
 },
 "panels": [
  { "title": "$deviceName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "deviceName" },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "select": [
      [
       { "params": [ "temperatureSensor1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "alias": "humidity",
     "measurement": "data",
     "select": [
      [
       { "params": [ "temperatureSensor1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "alias": "Pressure",
     "measurement": "data",
     "select": [
      [
       { "params": [ "barometer0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Output",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "digital outout",
     "measurement": "data",
     "select": [
      [
       { "params": [ "digitalOutput4" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Input",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "digital input",
     "measurement": "data",
     "select": [
      [
       { "params": [ "digitalInput3" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "alias": "vdd",
     "measurement": "data",
     "select": [
      [
       { "params": [ "vdd" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "query": "SELECT mean(\"temperature\") FROM \"data\" WHERE (\"applicationName\" = 'INUCLEO' AND \"devEUI\" = '4883c7df30051c1b') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperatureSensor1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "dew point",
     "measurement": "data",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "humidity",
     "measurement": "data",
     "select": [
      [
       { "params": [ "humiditySensor2" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "pressure",
     "measurement": "data",
     "select": [
      [
       { "params": [ "barometer0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Switch On/Off",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Digital",
     "measurement": "data",
     "select": [
      [
       { "params": [ "digitalOutput4" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "fCnt",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "fCnt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "DataRate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "dr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "redundancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "status",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  }
 ]
}