{
 "title": "Mon dashboard",
 "time": { "from": "2021-04-05T17:58:37.606Z", "to": "2021-04-05T20:09:04.270Z" },
 "panels": [
  {
   "title": "Dernières alertes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "button",
     "query": "SELECT \"alert\", \"client\" FROM \"sixty_days\".\"button\" WHERE (\"alertValid\" = '1') AND $timeFilter",
     "select": [
      [
       { "params": [ "alert" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ],
      [
       { "params": [ "client" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "alertValid", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Localisation des alertes",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "measurement": "button",
     "query": "SELECT \"metric\", \"latitude\", \"longitude\" FROM \"sixty_days\".\"button\" WHERE (\"alertValid\" = '1') AND $timeFilter GROUP BY \"metric\", \"latitude\", \"longitude\"",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" }
      ],
      [
       { "params": [ "longitude" ], "type": "field" }
      ],
      [
       { "params": [ "country" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "alertValid", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Alertes au cours du temps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "button",
     "select": [
      [
       { "params": [ "alert" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alertValid", "operator": "=", "value": "1" }
     ]
    }
   ]
  }
 ]
}